# Generated by Django 4.1.7 on 2023-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=255),
        ),
    ]
