# Generated by Django 4.1.7 on 2023-03-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_alter_task_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-date"]},
        ),
    ]
