# Generated by Django 4.1.7 on 2023-03-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-is_done", "-date"]},
        ),
    ]
